# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deep-dive',
                'doc_host': 'https://antelope134.github.io',
                'git_url': 'https://github.com/antelope134/deep-dive',
                'lib_path': 'deep_dive'},
  'syms': {'deep_dive.core': {'deep_dive.core.foo': ('core.html#foo', 'deep_dive/core.py')}}}
